// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.Pipeline -- run generate
// ManifestSha256: a69279876fdd1cc8c992b344ebe9479bf26bae7ac32d1101ca3d5bdbf795f751
#nullable enable
using System.Runtime.CompilerServices;

namespace Novolis.Raylib;
/// <summary>
/// Dear ImGui immediate-mode UI (cimgui + raylib-cimgui); after scene/HUD, before EndDrawing.
/// </summary>
public static partial class Gui
{
    /// <summary>
    /// Initializes ImGui and the raylib backend (call once after window init).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Setup(bool darkTheme = true) => GuiControls.Setup(darkTheme);
    /// <summary>
    /// Shuts down ImGui and releases backend resources.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Shutdown() => GuiControls.Shutdown();
    /// <summary>
    /// Starts a new ImGui frame (call after BeginDrawing, before widgets).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void NewFrame() => GuiControls.NewFrame();
    /// <summary>
    /// Submits ImGui draw data to raylib (call after widgets, before EndDrawing).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Render() => GuiControls.Render();
    /// <summary>
    /// Begins an ImGui window; returns false when collapsed.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool BeginWindow(string title, ref bool open) => GuiControls.BeginWindow(title, ref open);
    /// <summary>
    /// Ends the current ImGui window.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void EndWindow() => GuiControls.EndWindow();
    /// <summary>
    /// ImGui button; returns true when pressed.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Button(string label) => GuiControls.Button(label);
    /// <summary>
    /// Draws static ImGui text.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Text(string text) => GuiControls.Text(text);
    /// <summary>
    /// ImGui checkbox; returns true when toggled.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Checkbox(string label, ref bool value) => GuiControls.Checkbox(label, ref value);
    /// <summary>
    /// ImGui float slider.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Slider(string label, ref float value, float min, float max) => GuiControls.Slider(label, ref value, min, max);
    /// <summary>
    /// Continues layout on the same line.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SameLine(float offsetFromStartX = 0, float spacing = -1) => GuiControls.SameLine(offsetFromStartX, spacing);
    /// <summary>
    /// Draws a horizontal separator.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Separator() => GuiControls.Separator();
}
