// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 9fbd3e271969a8fdc9c68f946615ca4fb1257ec0cae9e534abd9df23bb74747b
#nullable enable
using System.Drawing;
using System.Numerics;
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Rendering;
/// <summary>
/// Texture load, draw, and unload helpers.
/// </summary>
public static partial class Textures
{
    /// <summary>
    /// Load texture from file into GPU memory (VRAM)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Texture Load(string fileName) => Texture.FromNative(Raylib6Native.LoadTexture(fileName));
    /// <summary>
    /// Unload texture from GPU memory (VRAM)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Unload(Texture texture) => Raylib6Native.UnloadTexture(texture.Native);
    /// <summary>
    /// Check if a texture is valid (loaded in GPU)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsValid(Texture texture) => Raylib6Native.IsTextureValid(texture.Native);
    /// <summary>
    /// Draw a Texture2D
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Draw(Texture texture, int posX, int posY, Color tint) => Raylib6Native.DrawTexture(texture.Native, posX, posY, tint.ToRaylibColor());
    /// <summary>
    /// Draw a part of a texture defined by a rectangle with 'pro' parameters
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawPro(Texture texture, RectangleF source, RectangleF dest, Vector2 origin, float rotation, Color tint) => Raylib6Native.DrawTexturePro(texture.Native, source, dest, origin, rotation, tint.ToRaylibColor());
}
