// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: f3c88e0e8244512cf130f0ff29b862755f849b2b1701d23d00f25870374c1452
#nullable enable
using System.Drawing;
using System.Numerics;
using Novolis.Raylib.Interop;
using Novolis.Raylib.Rendering;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Rendering;
/// <summary>
/// 3D scene rendering; call Begin with a Camera, then draw, then End.
/// </summary>
public static partial class World
{
    /// <summary>
    /// Begin 3D mode with custom camera (3D)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Begin(Camera camera) => Raylib6Native.BeginMode3D(camera);
    /// <summary>
    /// Ends 3D mode and returns to default 2D orthographic mode
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void End() => Raylib6Native.EndMode3D();
    /// <summary>
    /// Draw cube
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCube(Vector3 position, float width, float height, float length, Color color) => Raylib6Native.DrawCube(position, width, height, length, color.ToRaylibColor());
    /// <summary>
    /// Draw cube (Vector version)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCubeV(Vector3 position, Vector3 size, Color color) => Raylib6Native.DrawCubeV(position, size, color.ToRaylibColor());
    /// <summary>
    /// Draw cube wires (Vector version)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCubeWiresV(Vector3 position, Vector3 size, Color color) => Raylib6Native.DrawCubeWiresV(position, size, color.ToRaylibColor());
    /// <summary>
    /// Draw sphere
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawSphere(Vector3 centerPos, float radius, Color color) => Raylib6Native.DrawSphere(centerPos, radius, color.ToRaylibColor());
    /// <summary>
    /// Draw sphere wires
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawSphereWires(Vector3 centerPos, float radius, int rings, int slices, Color color) => Raylib6Native.DrawSphereWires(centerPos, radius, rings, slices, color.ToRaylibColor());
    /// <summary>
    /// Draw a line in 3D world space
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawLine(Vector3 startPos, Vector3 endPos, Color color) => Raylib6Native.DrawLine3D(startPos, endPos, color.ToRaylibColor());
    /// <summary>
    /// Draw a cylinder/cone
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawCylinder(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color) => Raylib6Native.DrawCylinder(position, radiusTop, radiusBottom, height, slices, color.ToRaylibColor());
    /// <summary>
    /// Draw a grid (centered at (0, 0, 0))
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawGrid(int slices, float spacing) => Raylib6Native.DrawGrid(slices, spacing);
    /// <summary>
    /// Draw a plane on the XZ axis
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawPlane(Vector3 centerPos, Vector2 size, Color color) => Raylib6Native.DrawPlane(centerPos, size, color.ToRaylibColor());
    /// <summary>
    /// Draw a camera-facing billboard texture
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawBillboard(Camera camera, Texture texture, Vector3 position, float scale, Color tint) => Raylib6Native.DrawBillboard(camera, texture.Native, position, scale, tint.ToRaylibColor());
    /// <summary>
    /// Draw a billboard with source rect, size, and rotation
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void DrawBillboardPro(Camera camera, Texture texture, RectangleF source, Vector3 position, Vector3 up, Vector2 size, Vector2 origin, float rotation, Color tint) => Raylib6Native.DrawBillboardPro(camera, texture.Native, source, position, up, size, origin, rotation, tint.ToRaylibColor());
}
