// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.Pipeline -- run generate
// ManifestSha256: 64c75d63de91704dfd863bc60d2a7bf98381b734671b7372c8b7a42362416e94
#nullable enable
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Audio;
/// <summary>
/// Audio device initialization.
/// </summary>
public static partial class AudioDevice
{
    /// <summary>
    /// Initialize audio device and context
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Init() => Raylib6Native.InitAudioDevice();
    /// <summary>
    /// Close the audio device and context
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Close() => Raylib6Native.CloseAudioDevice();
}
