// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.Pipeline -- run generate
// ManifestSha256: 2bc67efb82d5d6d14ff4bec75ecf36659e7b4a488aba15295b50d2afe36d1cad
#nullable enable
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Audio;
/// <summary>
/// Audio device initialization.
/// </summary>
public static partial class AudioDevice
{
    /// <summary>
    /// Initialize audio device and context
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Init() => Raylib6Native.InitAudioDevice();
    /// <summary>
    /// Close the audio device and context
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Close() => Raylib6Native.CloseAudioDevice();
}
