// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 9fbd3e271969a8fdc9c68f946615ca4fb1257ec0cae9e534abd9df23bb74747b
#nullable enable
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Audio;
/// <summary>
/// Audio device initialization.
/// </summary>
public static partial class AudioDevice
{
    /// <summary>
    /// Initialize audio device and context
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Init() => Raylib6Native.InitAudioDevice();
    /// <summary>
    /// Close the audio device and context
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Close() => Raylib6Native.CloseAudioDevice();
}
