using System.Text;
using Novolis.CodeGen.Bindings;

namespace Novolis.Raylib.CodeGen;

internal static class RaylibDebugHooksEmitter
{
    public static string Emit(DebugConfigFragment fragment, string manifestSha256)
    {
        var s = fragment.Symbols;
        if (string.IsNullOrEmpty(s.LoadImageFromScreen) || string.IsNullOrEmpty(s.ExportImageToMemory) ||
            string.IsNullOrEmpty(s.UnloadImage) || string.IsNullOrEmpty(s.MemFree))
        {
            throw new InvalidOperationException(
                "Manifest symbols.loadImageFromScreen, exportImageToMemory, unloadImage, memFree are required.");
        }

        var envVar = string.IsNullOrWhiteSpace(fragment.CaptureEnvVar) ? "NOVOLIS_RAYLIB_DEBUG_CAPTURE" : fragment.CaptureEnvVar;
        var pngType = string.IsNullOrWhiteSpace(fragment.CapturePngFileType) ? ".png" : fragment.CapturePngFileType;
        var notify = fragment.NotifyAfterNativeCall;
        var load = s.LoadImageFromScreen;
        var export = s.ExportImageToMemory;
        var unload = s.UnloadImage;
        var memFree = s.MemFree;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Regenerate: {CodegenHeaders.RegenerateHint}");
        sb.AppendLine($"// ManifestSha256: {manifestSha256}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Novolis.Raylib.Interop;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Debug-only hooks for automation / diagnostics. Native calls use manifest-defined <see cref=\"Raylib6Native\"/> entry points.</summary>");
        sb.AppendLine("internal static partial class RaylibDebugFrameHooks");
        sb.AppendLine("{");
        sb.AppendLine($"    internal const string CaptureEnvironmentVariable = \"{EscapeCSharpString(envVar)}\";");
        sb.AppendLine();
        sb.AppendLine("#if DEBUG");
        sb.AppendLine($"    /// <summary>Invoked on the render thread immediately after <see cref=\"Raylib6Native.{notify}\"/> from façade code.</summary>");
        sb.AppendLine($"    public static event Action? After{notify};");
        sb.AppendLine("#endif");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Notify subscribers after the configured native call (<c>notifyAfterNativeCall</c>).</summary>");
        sb.AppendLine($"    internal static void NotifyAfter{notify}()");
        sb.AppendLine("    {");
        sb.AppendLine("#if DEBUG");
        sb.AppendLine($"        After{notify}?.Invoke();");
        sb.AppendLine("#endif");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("#if DEBUG");
        sb.AppendLine($"    /// <summary>When <see cref=\"RaylibDebugCaptureGate.ProgrammaticEnabled\"/> is set or <see cref=\"CaptureEnvironmentVariable\"/> is <c>1</c>/<c>true</c>/<c>yes</c>, captures the framebuffer to PNG bytes in memory (raylib <c>{load}</c> / <c>{export}</c>).</summary>");
        sb.AppendLine("    internal static bool TryCaptureFramePng([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out byte[]? png)");
        sb.AppendLine("    {");
        sb.AppendLine("        png = null;");
        sb.AppendLine("        if (!RaylibDebugCaptureGate.IsRequested(CaptureEnvironmentVariable))");
        sb.AppendLine("            return false;");
        sb.AppendLine();
        sb.AppendLine($"        var image = Raylib6Native.{load}();");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            var ptr = Raylib6Native.{export}(image, \"{EscapeCSharpString(pngType)}\", out var size);");
        sb.AppendLine("            if (ptr == 0 || size <= 0)");
        sb.AppendLine("                return false;");
        sb.AppendLine("            png = new byte[size];");
        sb.AppendLine("            Marshal.Copy(ptr, png, 0, size);");
        sb.AppendLine($"            Raylib6Native.{memFree}(ptr);");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        finally");
        sb.AppendLine("        {");
        sb.AppendLine($"            Raylib6Native.{unload}(image);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("#else");
        sb.AppendLine("    internal static bool TryCaptureFramePng(out byte[]? png)");
        sb.AppendLine("    {");
        sb.AppendLine("        png = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine("#endif");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeCSharpString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
