using Novolis.CodeGen.Bindings;

namespace Novolis.Raylib.Manifests;

public static partial class RaylibBindingManifests
{
    public static InteropExportsFragment Raylib6Interop { get; } = new(
        Id: "raylib6",
        SchemaVersion: 2,
        Header: "codegen/vendor/raylib-6/include/raylib.h",
        Description: "Authoritative raylib 6 LibraryImport surface.",
        DllName: "raylib",
        Policy: new(
            SuppressGcTransitionByFunction: [],
            NeverSuppressGcTransition: new string[]
            {
                "ExportImageToMemory",
                "MemFree",
                "LoadTexture",
            },
            FacadeMethodImpl: "AggressiveInlining",
            UseDisableRuntimeMarshalling: true),
        Structs: new InteropStructSpec[]
        {
            new("Raylib6NativeImage", new InteropFieldSpec[] { new("Data", "nint"), new("Width", "int"), new("Height", "int"), new("Mipmaps", "int"), new("Format", "int") }),
            new("Raylib6NativeTexture", new InteropFieldSpec[] { new("Id", "uint"), new("Width", "int"), new("Height", "int"), new("Mipmaps", "int"), new("Format", "int") }),
        },
        Imports: new InteropImportSpec[]
        {
            new("BeginDrawing", RaylibNativeSignatures.VoidVoid),
            new("BeginMode3D", RaylibNativeSignatures.VoidCamera),
            new("BeginScissorMode", RaylibNativeSignatures.VoidRectInts),
            new("ClearBackground", RaylibNativeSignatures.VoidColor),
            new("CloseAudioDevice", RaylibNativeSignatures.VoidVoid),
            new("CloseWindow", RaylibNativeSignatures.VoidVoid),
            new("DisableCursor", RaylibNativeSignatures.VoidVoid),
            new("DrawCircle", RaylibNativeSignatures.VoidIntIntFloatColor),
            new("DrawCube", RaylibNativeSignatures.VoidVector3FloatFloatFloatColor),
            new("DrawCubeV", RaylibNativeSignatures.VoidVector3Vector3Color),
            new("DrawCubeWiresV", RaylibNativeSignatures.VoidVector3Vector3Color),
            new("DrawCylinder", RaylibNativeSignatures.VoidVector3FloatFloatFloatIntColor),
            new("DrawFPS", RaylibNativeSignatures.VoidIntInt),
            new("DrawBillboard", RaylibNativeSignatures.VoidCameraTextureVector3FloatColor),
            new("DrawBillboardPro", RaylibNativeSignatures.VoidCameraTextureRectangleVector3Vector2Vector2Vector2FloatColor),
            new("DrawGrid", RaylibNativeSignatures.VoidIntFloat),
            new("DrawPlane", RaylibNativeSignatures.VoidVector3Vector2Color),
            new("DrawLine", RaylibNativeSignatures.VoidIntIntIntIntColor),
            new("DrawLine3D", RaylibNativeSignatures.VoidVector3Vector3Color),
            new("DrawRectangle", RaylibNativeSignatures.VoidIntIntIntIntColor),
            new("DrawRectangleLines", RaylibNativeSignatures.VoidIntIntIntIntColor),
            new("DrawRectangleRec", RaylibNativeSignatures.VoidRectangleColor),
            new("DrawSphere", RaylibNativeSignatures.VoidVector3FloatColor),
            new("DrawSphereWires", RaylibNativeSignatures.VoidVector3FloatIntIntColor),
            new("DrawTriangle3D", RaylibNativeSignatures.VoidVector3Vector3Vector3Color),
            new("DrawText", RaylibNativeSignatures.VoidUtf8IntIntIntColor),
            new("DrawTexture", RaylibNativeSignatures.VoidTextureIntIntColor),
            new("DrawTexturePro", RaylibNativeSignatures.VoidTextureRectangleRectangleVector2FloatColor),
            new("EnableCursor", RaylibNativeSignatures.VoidVoid),
            new("EndDrawing", RaylibNativeSignatures.VoidVoid),
            new("EndMode3D", RaylibNativeSignatures.VoidVoid),
            new("EndScissorMode", RaylibNativeSignatures.VoidVoid),
            new("ExportImageToMemory", RaylibNativeSignatures.NativeIntImageUtf8OutInt),
            new("GetCharPressed", RaylibNativeSignatures.IntVoid),
            new("GetFrameTime", RaylibNativeSignatures.FloatVoid),
            new("GetKeyPressed", RaylibNativeSignatures.IntVoid),
            new("GetMouseDelta", RaylibNativeSignatures.Vector2Void),
            new("GetMousePosition", RaylibNativeSignatures.Vector2Void),
            new("GetMouseWheelMove", RaylibNativeSignatures.FloatVoid),
            new("GetScreenHeight", RaylibNativeSignatures.IntVoid),
            new("GetScreenWidth", RaylibNativeSignatures.IntVoid),
            new("InitAudioDevice", RaylibNativeSignatures.VoidVoid),
            new("InitWindow", RaylibNativeSignatures.VoidIntIntUtf8),
            new("IsCursorOnScreen", RaylibNativeSignatures.BoolVoid),
            new("IsKeyDown", RaylibNativeSignatures.BoolInt),
            new("IsKeyPressed", RaylibNativeSignatures.BoolInt),
            new("IsKeyReleased", RaylibNativeSignatures.BoolInt),
            new("IsMouseButtonDown", RaylibNativeSignatures.BoolInt),
            new("IsMouseButtonPressed", RaylibNativeSignatures.BoolInt),
            new("IsTextureValid", RaylibNativeSignatures.BoolTexture),
            new("IsWindowFullscreen", RaylibNativeSignatures.BoolVoid),
            new("IsWindowHidden", RaylibNativeSignatures.BoolVoid),
            new("IsWindowReady", RaylibNativeSignatures.BoolVoid),
            new("LoadImageFromScreen", RaylibNativeSignatures.ImageVoid),
            new("LoadTexture", RaylibNativeSignatures.TextureUtf8),
            new("MeasureText", RaylibNativeSignatures.IntUtf8Int),
            new("MemFree", RaylibNativeSignatures.VoidNativeInt),
            new("PollInputEvents", RaylibNativeSignatures.VoidVoid),
            new("SetConfigFlags", RaylibNativeSignatures.VoidUInt),
            new("SetExitKey", RaylibNativeSignatures.VoidInt),
            new("SetMousePosition", RaylibNativeSignatures.VoidIntInt),
            new("SetTargetFPS", RaylibNativeSignatures.VoidInt),
            new("SetTraceLogLevel", RaylibNativeSignatures.VoidInt),
            new("SetWindowState", RaylibNativeSignatures.VoidUInt),
            new("SetWindowTitle", RaylibNativeSignatures.VoidUtf8),
            new("ToggleFullscreen", RaylibNativeSignatures.VoidVoid),
            new("UnloadImage", RaylibNativeSignatures.VoidImage),
            new("UnloadTexture", RaylibNativeSignatures.VoidTexture),
            new("WindowShouldClose", RaylibNativeSignatures.BoolVoid),
        },
        Usings:
        [
            "System.Drawing",
            "System.Numerics",
            "Novolis.Raylib.Interop",
            "Novolis.Raylib.Rendering",
        ]
    );
}
