using Novolis.CodeGen.Bindings;

namespace Novolis.Raylib.Manifests;

public static partial class RaylibBindingManifests
{
    public static InteropExportsFragment Raylib6Interop { get; } = new(
        Id: "raylib6",
        SchemaVersion: 2,
        Header: "codegen/vendor/raylib-6/include/raylib.h",
        Description: "Authoritative raylib 6 LibraryImport surface. Sorted by name; templates map to generate-raylib-interop.cs emit logic.",
        DllName: "raylib",
        Policy: new(
            SuppressGcTransitionByTemplate: new string[]
            {
                "void_void",
                "void_color",
                "void_int",
                "void_uint",
                "bool_int",
                "bool_void",
                "int_void",
                "float_void",
                "vector2_void",
                "void_int_int_int_int",
                "void_int_int_float_color",
                "void_int_int_int_int_color",
                "void_rectangle_color",
                "void_int_int",
                "image_void",
                "void_image",
                "void_camera3d",
                "void_vector3_float_float_float_color",
                "void_vector3_vector3_color",
                "void_vector3_float_color",
                "void_vector3_float_int_int_color",
                "void_vector3_float_float_float_int_color",
                "void_vector3_vector2_color",
                "void_camera_texture_vector3_float_color",
                "void_camera_texture_rectangle_vector3_vector2_vector2_vector2_float_color",
                "void_int_float",
                "void_texture",
                "bool_texture",
                "void_texture_int_int_color",
                "void_texture_rectangle_rectangle_vector2_float_color",
            },
            NeverSuppressGcTransition: new string[]
            {
                "ExportImageToMemory",
                "MemFree",
                "LoadTexture",
            },
            FacadeMethodImpl: "AggressiveInlining",
            UseDisableRuntimeMarshalling: true),
        Structs: new InteropStructSpec[]
        {
            new("Raylib6NativeImage", new InteropFieldSpec[] { new("Data", "nint"), new("Width", "int"), new("Height", "int"), new("Mipmaps", "int"), new("Format", "int") }),
            new("Raylib6NativeTexture", new InteropFieldSpec[] { new("Id", "uint"), new("Width", "int"), new("Height", "int"), new("Mipmaps", "int"), new("Format", "int") }),
        },
        Imports: new InteropImportSpec[]
        {
            new("BeginDrawing", "void_void"),
            new("BeginMode3D", "void_camera3d"),
            new("BeginScissorMode", "void_int_int_int_int"),
            new("ClearBackground", "void_color"),
            new("CloseAudioDevice", "void_void"),
            new("CloseWindow", "void_void"),
            new("DisableCursor", "void_void"),
            new("DrawCircle", "void_int_int_float_color"),
            new("DrawCube", "void_vector3_float_float_float_color"),
            new("DrawCubeV", "void_vector3_vector3_color"),
            new("DrawCubeWiresV", "void_vector3_vector3_color"),
            new("DrawCylinder", "void_vector3_float_float_float_int_color"),
            new("DrawFPS", "void_int_int"),
            new("DrawBillboard", "void_camera_texture_vector3_float_color"),
            new("DrawBillboardPro", "void_camera_texture_rectangle_vector3_vector2_vector2_vector2_float_color"),
            new("DrawGrid", "void_int_float"),
            new("DrawPlane", "void_vector3_vector2_color"),
            new("DrawLine", "void_int_int_int_int_color"),
            new("DrawLine3D", "void_vector3_vector3_color"),
            new("DrawRectangle", "void_int_int_int_int_color"),
            new("DrawRectangleLines", "void_int_int_int_int_color"),
            new("DrawRectangleRec", "void_rectangle_color"),
            new("DrawSphere", "void_vector3_float_color"),
            new("DrawSphereWires", "void_vector3_float_int_int_color"),
            new("DrawText", "void_string_utf8_int_int_int_color"),
            new("DrawTexture", "void_texture_int_int_color"),
            new("DrawTexturePro", "void_texture_rectangle_rectangle_vector2_float_color"),
            new("EnableCursor", "void_void"),
            new("EndDrawing", "void_void"),
            new("EndMode3D", "void_void"),
            new("EndScissorMode", "void_void"),
            new("ExportImageToMemory", "nint_image_string_utf8_out_int"),
            new("GetCharPressed", "int_void"),
            new("GetFrameTime", "float_void"),
            new("GetKeyPressed", "int_void"),
            new("GetMouseDelta", "vector2_void"),
            new("GetMousePosition", "vector2_void"),
            new("GetMouseWheelMove", "float_void"),
            new("GetScreenHeight", "int_void"),
            new("GetScreenWidth", "int_void"),
            new("InitAudioDevice", "void_void"),
            new("InitWindow", "void_int_int_string_utf8"),
            new("IsCursorOnScreen", "bool_void"),
            new("IsKeyDown", "bool_int"),
            new("IsKeyPressed", "bool_int"),
            new("IsKeyReleased", "bool_int"),
            new("IsMouseButtonDown", "bool_int"),
            new("IsMouseButtonPressed", "bool_int"),
            new("IsTextureValid", "bool_texture"),
            new("IsWindowFullscreen", "bool_void"),
            new("IsWindowHidden", "bool_void"),
            new("IsWindowReady", "bool_void"),
            new("LoadImageFromScreen", "image_void"),
            new("LoadTexture", "texture_string_utf8"),
            new("MeasureText", "int_string_utf8_int"),
            new("MemFree", "void_nint"),
            new("PollInputEvents", "void_void"),
            new("SetConfigFlags", "void_uint"),
            new("SetExitKey", "void_int"),
            new("SetMousePosition", "void_int_int"),
            new("SetTargetFPS", "void_int"),
            new("SetTraceLogLevel", "void_int"),
            new("SetWindowState", "void_uint"),
            new("SetWindowTitle", "void_string_utf8"),
            new("ToggleFullscreen", "void_void"),
            new("UnloadImage", "void_image"),
            new("UnloadTexture", "void_texture"),
            new("WindowShouldClose", "bool_void"),
        }
    );
}
