// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 9fbd3e271969a8fdc9c68f946615ca4fb1257ec0cae9e534abd9df23bb74747b
#nullable enable
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Timing;
/// <summary>
/// Frame timing and target FPS.
/// </summary>
public static partial class Time
{
    /// <summary>
    /// Set target FPS (maximum)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetTargetFPS(int fps) => Raylib6Native.SetTargetFPS(fps);
    /// <summary>
    /// Get time in seconds for last frame drawn (delta time)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float GetFrameTime() => Raylib6Native.GetFrameTime();
}
