// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.Pipeline -- run generate
// ManifestSha256: f3c88e0e8244512cf130f0ff29b862755f849b2b1701d23d00f25870374c1452
#nullable enable
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Timing;
/// <summary>
/// Frame timing and target FPS.
/// </summary>
public static partial class Time
{
    /// <summary>
    /// Set target FPS (maximum)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetTargetFPS(int fps) => Raylib6Native.SetTargetFPS(fps);
    /// <summary>
    /// Get time in seconds for last frame drawn (delta time)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float GetFrameTime() => Raylib6Native.GetFrameTime();
}
