// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.Pipeline -- run generate
// ManifestSha256: 64c75d63de91704dfd863bc60d2a7bf98381b734671b7372c8b7a42362416e94
#nullable enable
using Novolis.Raylib.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib.Timing;
/// <summary>
/// Frame timing and target FPS.
/// </summary>
public static partial class Time
{
    /// <summary>
    /// Set target FPS (maximum)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetTargetFPS(int fps) => Raylib6Native.SetTargetFPS(fps);
    /// <summary>
    /// Get time in seconds for last frame drawn (delta time)
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float GetFrameTime() => Raylib6Native.GetFrameTime();
}
