// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.CodeGen -- generate
// ManifestSha256: 5d7aec508b5dda34273c9b310c6a989511ac0d93dfc340c8334220cd492251f0
#nullable enable
using System.Runtime.InteropServices;

namespace Novolis.Raylib.Interop;
internal static unsafe partial class ImguiShimExports
{
    internal static delegate* unmanaged<byte*, int*, int, int> novolis_igBegin_ptr;
    internal static delegate* unmanaged<byte*, int> novolis_igButton_ptr;
    internal static delegate* unmanaged<byte*, int*, int> novolis_igCheckbox_ptr;
    internal static delegate* unmanaged<void> novolis_igEnd_ptr;
    internal static delegate* unmanaged<float, float, void> novolis_igSameLine_ptr;
    internal static delegate* unmanaged<void> novolis_igSeparator_ptr;
    internal static delegate* unmanaged<byte*, float*, float, float, int> novolis_igSliderFloat_ptr;
    internal static delegate* unmanaged<byte*, void> novolis_igText_ptr;
    internal static delegate* unmanaged<void> novolis_rlimgui_begin_ptr;
    internal static delegate* unmanaged<void> novolis_rlimgui_end_ptr;
    internal static delegate* unmanaged<int, void> novolis_rlimgui_setup_ptr;
    internal static delegate* unmanaged<void> novolis_rlimgui_shutdown_ptr;
    internal static bool TryBindShim(nint module, out string? error)
    {
        error = null;
        var pnovolis_igBegin = NativeLibrary.GetExport(module, "novolis_igBegin");
        if (pnovolis_igBegin == 0)
        {
            error = "Missing export: novolis_igBegin";
            return false;
        }

        novolis_igBegin_ptr = (delegate* unmanaged<byte*, int*, int, int> )pnovolis_igBegin;
        var pnovolis_igButton = NativeLibrary.GetExport(module, "novolis_igButton");
        if (pnovolis_igButton == 0)
        {
            error = "Missing export: novolis_igButton";
            return false;
        }

        novolis_igButton_ptr = (delegate* unmanaged<byte*, int> )pnovolis_igButton;
        var pnovolis_igCheckbox = NativeLibrary.GetExport(module, "novolis_igCheckbox");
        if (pnovolis_igCheckbox == 0)
        {
            error = "Missing export: novolis_igCheckbox";
            return false;
        }

        novolis_igCheckbox_ptr = (delegate* unmanaged<byte*, int*, int> )pnovolis_igCheckbox;
        var pnovolis_igEnd = NativeLibrary.GetExport(module, "novolis_igEnd");
        if (pnovolis_igEnd == 0)
        {
            error = "Missing export: novolis_igEnd";
            return false;
        }

        novolis_igEnd_ptr = (delegate* unmanaged<void> )pnovolis_igEnd;
        var pnovolis_igSameLine = NativeLibrary.GetExport(module, "novolis_igSameLine");
        if (pnovolis_igSameLine == 0)
        {
            error = "Missing export: novolis_igSameLine";
            return false;
        }

        novolis_igSameLine_ptr = (delegate* unmanaged<float, float, void> )pnovolis_igSameLine;
        var pnovolis_igSeparator = NativeLibrary.GetExport(module, "novolis_igSeparator");
        if (pnovolis_igSeparator == 0)
        {
            error = "Missing export: novolis_igSeparator";
            return false;
        }

        novolis_igSeparator_ptr = (delegate* unmanaged<void> )pnovolis_igSeparator;
        var pnovolis_igSliderFloat = NativeLibrary.GetExport(module, "novolis_igSliderFloat");
        if (pnovolis_igSliderFloat == 0)
        {
            error = "Missing export: novolis_igSliderFloat";
            return false;
        }

        novolis_igSliderFloat_ptr = (delegate* unmanaged<byte*, float*, float, float, int> )pnovolis_igSliderFloat;
        var pnovolis_igText = NativeLibrary.GetExport(module, "novolis_igText");
        if (pnovolis_igText == 0)
        {
            error = "Missing export: novolis_igText";
            return false;
        }

        novolis_igText_ptr = (delegate* unmanaged<byte*, void> )pnovolis_igText;
        var pnovolis_rlimgui_begin = NativeLibrary.GetExport(module, "novolis_rlimgui_begin");
        if (pnovolis_rlimgui_begin == 0)
        {
            error = "Missing export: novolis_rlimgui_begin";
            return false;
        }

        novolis_rlimgui_begin_ptr = (delegate* unmanaged<void> )pnovolis_rlimgui_begin;
        var pnovolis_rlimgui_end = NativeLibrary.GetExport(module, "novolis_rlimgui_end");
        if (pnovolis_rlimgui_end == 0)
        {
            error = "Missing export: novolis_rlimgui_end";
            return false;
        }

        novolis_rlimgui_end_ptr = (delegate* unmanaged<void> )pnovolis_rlimgui_end;
        var pnovolis_rlimgui_setup = NativeLibrary.GetExport(module, "novolis_rlimgui_setup");
        if (pnovolis_rlimgui_setup == 0)
        {
            error = "Missing export: novolis_rlimgui_setup";
            return false;
        }

        novolis_rlimgui_setup_ptr = (delegate* unmanaged<int, void> )pnovolis_rlimgui_setup;
        var pnovolis_rlimgui_shutdown = NativeLibrary.GetExport(module, "novolis_rlimgui_shutdown");
        if (pnovolis_rlimgui_shutdown == 0)
        {
            error = "Missing export: novolis_rlimgui_shutdown";
            return false;
        }

        novolis_rlimgui_shutdown_ptr = (delegate* unmanaged<void> )pnovolis_rlimgui_shutdown;
        return true;
    }
}
