<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Novolis.Raylib.Golden.Seed</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
    <EnableTestingPlatform>false</EnableTestingPlatform>
    <EnableMicrosoftTestingPlatform>false</EnableMicrosoftTestingPlatform>
    <UseMicrosoftTestingPlatform>false</UseMicrosoftTestingPlatform>
    <DisableTestingPlatformServerCapability>true</DisableTestingPlatformServerCapability>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Novolis.Raylib.Testing\Novolis.Raylib.Testing.csproj" />
  </ItemGroup>

</Project>
