// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Raylib.Pipeline -- run generate
// ManifestSha256: 6ffa577887316948f301acc0799259a505b267bb8b28dcff272fde54ff51e8e6
#nullable enable
using System.Drawing;
using System.Runtime.CompilerServices;

namespace Novolis.Raylib;
/// <summary>
/// raygui immediate-mode widgets (UTF-8); optional add-on; draw after scene and HUD, before EndDrawing.
/// </summary>
public static partial class RayGui
{
    /// <summary>
    /// Enables raygui controls (global state).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Enable() => RayGuiControls.Enable();
    /// <summary>
    /// Disables raygui controls (global state).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Disable() => RayGuiControls.Disable();
    /// <summary>
    /// Locks raygui controls (global state).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Lock() => RayGuiControls.Lock();
    /// <summary>
    /// Unlocks raygui controls (global state).
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Unlock() => RayGuiControls.Unlock();
    /// <summary>
    /// Sets global raygui alpha.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetAlpha(float alpha) => RayGuiControls.SetAlpha(alpha);
    /// <summary>
    /// Loads default raygui style.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void LoadStyleDefault() => RayGuiControls.LoadStyleDefault();
    /// <summary>
    /// raygui button; returns true when pressed.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Button(RectangleF bounds, string label) => RayGuiControls.Button(bounds, label);
    /// <summary>
    /// raygui static label.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Label(RectangleF bounds, string text) => RayGuiControls.Label(bounds, text);
    /// <summary>
    /// raygui panel with title.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Panel(RectangleF bounds, string title) => RayGuiControls.Panel(bounds, title);
    /// <summary>
    /// raygui group box with title.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void GroupBox(RectangleF bounds, string title) => RayGuiControls.GroupBox(bounds, title);
    /// <summary>
    /// raygui toggle control.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Toggle(RectangleF bounds, string label, ref bool active) => RayGuiControls.Toggle(bounds, label, ref active);
    /// <summary>
    /// raygui checkbox.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool CheckBox(RectangleF bounds, string label, ref bool active) => RayGuiControls.CheckBox(bounds, label, ref active);
    /// <summary>
    /// raygui combo box.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool ComboBox(RectangleF bounds, string text, ref int active) => RayGuiControls.ComboBox(bounds, text, ref active);
    /// <summary>
    /// raygui slider with label.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Slider(RectangleF bounds, string label, ref float value, float min, float max) => RayGuiControls.Slider(bounds, label, ref value, min, max);
    /// <summary>
    /// raygui slider bar with label.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool SliderBar(RectangleF bounds, string label, ref float value, float min, float max) => RayGuiControls.SliderBar(bounds, label, ref value, min, max);
    /// <summary>
    /// raygui progress bar with label.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool ProgressBar(RectangleF bounds, string label, ref float value, float min, float max) => RayGuiControls.ProgressBar(bounds, label, ref value, min, max);
}
